package:
  name: genolearn
  version: 0.0.4

source:
  path: ../src

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - numpy>=1.21.5
    - scipy>=1.7.3
    - psutil>=5.8.0
    - scikit-learn>=1.1.2
    - python>=3.6

about:
  home: https://github.com/jordan-wei-taylor/genolearn
  license: BSD-3-Clause
  license_family: BSD
  summary: "A machine learning toolkit for genome sequence data"

extra:
  recipe-maintainers:
    - jordan-wei-taylor